### ISSUE TITLE
New Version 3-14-20 FileNotFoundException

### ISSUE THREAD

**Issue by bcbisme** [khoait/DynCrmExp.Deduplicator#20]
Getting the following in your upgrade.  Please see attached
![Deduplicator](https://user-images.githubusercontent.com/12277076/76785342-42f5c080-6783-11ea-8e0f-b60ffff8ea97.JPG)

**Comment by khoait** [comment]
Hi @bcbisme, thanks for using the plugin and giving your feedback. I decided to update CsvHelper to the latest version, looks like it doesn't like it :) I'll fix it soon and let you know.

**Comment by bcbisme** [comment]
Thank you Khoa ☺

**Comment by khoait** [comment]
Hi @bcbisme . This is fixed in v1.2020.3.18. Enjoy! :)

**Comment by C-Je** [comment]
Hello @khoait, I've run the a job today and it worked a treat - but I am still getting this issue. My error box is: 
![image](https://user-images.githubusercontent.com/76483124/102895527-bf2cdb00-445c-11eb-83b2-84aaec72e0b5.png)
This will be a huge help if you can guide me/resolve this.

**Comment by khoait** [comment]
Hi @C-Je, I think it's a different bug. Could you help open a new ticket and describe in details if possible what entity and fields you are working on? I'll try to work on it soon, maybe tomorrow or this week.

**Comment by C-Je** [comment]
Sure thing, thank you for the quick response. I'm now on A/L so won't be checking in on it until the earliest 4th Jan. Thanks so much.
